# Generated by Django 3.1.2 on 2023-06-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_carrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_carrito',
            name='subtotal',
        ),
    ]
