# Generated by Django 3.1.2 on 2023-06-01 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_item_carrito_subtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='tipo_subscripcion',
        ),
        migrations.AddField(
            model_name='subscription',
            name='suscrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='fecha_termino',
            field=models.DateField(auto_now_add=True),
        ),
    ]
