# Generated by Django 3.1.2 on 2023-06-01 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20230601_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscripciones',
        ),
    ]
