# Generated by Django 3.1.2 on 2023-06-01 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230601_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscripciones',
        ),
    ]
